In [1]:
import pandas as pd
import numpy as np

In [54]:
df = pd.read_csv('train.csv')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df.shape

(891, 12)

In [7]:
df.drop_duplicates(inplace=True)
df.dropna(inplace = True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [17]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [57]:
def print_correlation_list(df):
    for i in df.columns:
        if (df[i].dtype != object):
            print(i,"vs survived", df[i].corr(df['Survived']))

In [39]:
def Embarked_value(embark_place):
    ar = ['C','Q','S']
    return ar.index(embark_place)

In [56]:
featuresList = ["Pclass", "Age", "SibSp", "Parch", "Fare", "Survived"]
features = pd.DataFrame(columns = featuresList)
for i in featuresList:
    features[i] = df[i]

features["Sex"] = df['Sex'].apply(lambda x: 1 if x.lower() == 'male' else 0)
features["embark_value"] = df['Embarked'].apply(lambda x : Embarked_value(x))
features

     Pclass    Age  SibSp  Parch      Fare  Survived  Sex  embark_value
0         3  22.00      1      0    7.2500         0    1             2
1         1  38.00      1      0   71.2833         1    0             0
2         3  26.00      0      0    7.9250         1    0             2
3         1  35.00      1      0   53.1000         1    0             2
4         3  35.00      0      0    8.0500         0    1             2
5         3    NaN      0      0    8.4583         0    1             1
6         1  54.00      0      0   51.8625         0    1             2
7         3   2.00      3      1   21.0750         0    1             2
8         3  27.00      0      2   11.1333         1    0             2
9         2  14.00      1      0   30.0708         1    0             0
10        3   4.00      1      1   16.7000         1    0             2
11        1  58.00      0      0   26.5500         1    0             2
12        3  20.00      0      0    8.0500         0    1             2
13        3  39.00      1      5   31.2750         0    1             2
14        3  14.00      0      0    7.8542         0    0             2
15        2  55.00      0      0   16.0000         1    0             2
16        3   2.00      4      1   29.1250         0    1             1
17        2    NaN      0      0   13.0000         1    1             2
18        3  31.00      1      0   18.0000         0    0             2
19        3    NaN      0      0    7.2250         1    0             0
20        2  35.00      0      0   26.0000         0    1             2
21        2  34.00      0      0   13.0000         1    1             2
22        3  15.00      0      0    8.0292         1    0             1
23        1  28.00      0      0   35.5000         1    1             2
24        3   8.00      3      1   21.0750         0    0             2
25        3  38.00      1      5   31.3875         1    0             2
26        3    NaN      0      0    7.2250         0    1             0
27        1  19.00      3      2  263.0000         0    1             2
28        3    NaN      0      0    7.8792         1    0             1
29        3    NaN      0      0    7.8958         0    1             2
30        1  40.00      0      0   27.7208         0    1             0
31        1    NaN      1      0  146.5208         1    0             0
32        3    NaN      0      0    7.7500         1    0             1
33        2  66.00      0      0   10.5000         0    1             2
34        1  28.00      1      0   82.1708         0    1             0
35        1  42.00      1      0   52.0000         0    1             2
36        3    NaN      0      0    7.2292         1    1             0
37        3  21.00      0      0    8.0500         0    1             2
38        3  18.00      2      0   18.0000         0    0             2
39        3  14.00      1      0   11.2417         1    0             0
40        3  40.00      1      0    9.4750         0    0             2
41        2  27.00      1      0   21.0000         0    0             2
42        3    NaN      0      0    7.8958         0    1             0
43        2   3.00      1      2   41.5792         1    0             0
44        3  19.00      0      0    7.8792         1    0             1
45        3    NaN      0      0    8.0500         0    1             2
46        3    NaN      1      0   15.5000         0    1             1
47        3    NaN      0      0    7.7500         1    0             1
48        3    NaN      2      0   21.6792         0    1             0
49        3  18.00      1      0   17.8000         0    0             2
50        3   7.00      4      1   39.6875         0    1             2
51        3  21.00      0      0    7.8000         0    1             2
52        1  49.00      1      0   76.7292         1    0             0
53        2  29.00      1      0   26.0000         1    0             2
54        1  65.00      0      1   61.9792         0    1             0
55        1    NaN      0      0   35.5000         1    1             2
56        2  21.00      0      0   10.5000         1    0             2
57        3  28.50      0      0    7.2292         0    1             0
58        2   5.00      1      2   27.7500         1    0             2
59        3  11.00      5      2   46.9000         0    1             2
60        3  22.00      0      0    7.2292         0    1             0
62        1  45.00      1      0   83.4750         0    1             2
63        3   4.00      3      2   27.9000         0    1             2
64        1    NaN      0      0   27.7208         0    1             0
65        3    NaN      1      1   15.2458         1    1             0
66        2  29.00      0      0   10.5000         1    0             2
67        3  19.00      0      0    8.1583         0    1             2
68        3  17.00      4      2    7.9250         1    0             2
69        3  26.00      2      0    8.6625         0    1             2
70        2  32.00      0      0   10.5000         0    1             2
71        3  16.00      5      2   46.9000         0    0             2
72        2  21.00      0      0   73.5000         0    1             2
73        3  26.00      1      0   14.4542         0    1             0
74        3  32.00      0      0   56.4958         1    1             2
75        3  25.00      0      0    7.6500         0    1             2
76        3    NaN      0      0    7.8958         0    1             2
77        3    NaN      0      0    8.0500         0    1             2
78        2   0.83      0      2   29.0000         1    1             2
79        3  30.00      0      0   12.4750         1    0             2
80        3  22.00      0      0    9.0000         0    1             2
81        3  29.00      0      0    9.5000         1    1             2
82        3    NaN      0      0    7.7875         1    0             1
83        1  28.00      0      0   47.1000         0    1             2
84        2  17.00      0      0   10.5000         1    0             2
85        3  33.00      3      0   15.8500         1    0             2
86        3  16.00      1      3   34.3750         0    1             2
87        3    NaN      0      0    8.0500         0    1             2
88        1  23.00      3      2  263.0000         1    0             2
89        3  24.00      0      0    8.0500         0    1             2
90        3  29.00      0      0    8.0500         0    1             2
91        3  20.00      0      0    7.8542         0    1             2
92        1  46.00      1      0   61.1750         0    1             2
93        3  26.00      1      2   20.5750         0    1             2
94        3  59.00      0      0    7.2500         0    1             2
95        3    NaN      0      0    8.0500         0    1             2
96        1  71.00      0      0   34.6542         0    1             0
97        1  23.00      0      1   63.3583         1    1             0
98        2  34.00      0      1   23.0000         1    0             2
99        2  34.00      1      0   26.0000         0    1             2
100       3  28.00      0      0    7.8958         0    0             2
101       3    NaN      0      0    7.8958         0    1             2
102       1  21.00      0      1   77.2875         0    1             2
103       3  33.00      0      0    8.6542         0    1             2
104       3  37.00      2      0    7.9250         0    1             2
105       3  28.00      0      0    7.8958         0    1             2
106       3  21.00      0      0    7.6500         1    0             2
107       3    NaN      0      0    7.7750         1    1             2
108       3  38.00      0      0    7.8958         0    1             2
109       3    NaN      1      0   24.1500         1    0             1
110       1  47.00      0      0   52.0000         0    1             2
111       3  14.50      1      0   14.4542         0    0             0
112       3  22.00      0      0    8.0500         0    1             2
113       3  20.00      1      0    9.8250         0    0             2
114       3  17.00      0      0   14.4583         0    0             0
115       3  21.00      0      0    7.9250         0    1             2
116       3  70.50      0      0    7.7500         0    1             1
117       2  29.00      1      0   21.0000         0    1             2
118       1  24.00      0      1  247.5208         0    1             0
119       3   2.00      4      2   31.2750         0    0             2
120       2  21.00      2      0   73.5000         0    1             2
121       3    NaN      0      0    8.0500         0    1             2
122       2  32.50      1      0   30.0708         0    1             0
123       2  32.50      0      0   13.0000         1    0             2
124       1  54.00      0      1   77.2875         0    1             2
125       3  12.00      1      0   11.2417         1    1             0
126       3    NaN      0      0    7.7500         0    1             1
127       3  24.00      0      0    7.1417         1    1             2
128       3    NaN      1      1   22.3583         1    0             0
129       3  45.00      0      0    6.9750         0    1             2
130       3  33.00      0      0    7.8958         0    1             0
131       3  20.00      0      0    7.0500         0    1             2
132       3  47.00      1      0   14.5000         0    0             2
133       2  29.00      1      0   26.0000         1    0             2
134       2  25.00      0      0   13.0000         0    1             2
135       2  23.00      0      0   15.0458         0    1             0
136       1  19.00      0      2   26.2833         1    0             2
137       1  37.00      1      0   53.1000         0    1             2
138       3  16.00      0      0    9.2167         0    1             2
139       1  24.00      0      0   79.2000         0    1             0
140       3    NaN      0      2   15.2458         0    0             0
141       3  22.00      0      0    7.7500         1    0             2
142       3  24.00      1      0   15.8500         1    0             2
143       3  19.00      0      0    6.7500         0    1             1
144       2  18.00      0      0   11.5000         0    1             2
145       2  19.00      1      1   36.7500         0    1             2
146       3  27.00      0      0    7.7958         1    1             2
147       3   9.00      2      2   34.3750         0    0             2
148       2  36.50      0      2   26.0000         0    1             2
149       2  42.00      0      0   13.0000         0    1             2
150       2  51.00      0      0   12.5250         0    1             2
151       1  22.00      1      0   66.6000         1    0             2
152       3  55.50      0      0    8.0500         0    1             2
153       3  40.50      0      2   14.5000         0    1             2
154       3    NaN      0      0    7.3125         0    1             2
155       1  51.00      0      1   61.3792         0    1             0
156       3  16.00      0      0    7.7333         1    0             1
157       3  30.00      0      0    8.0500         0    1             2
158       3    NaN      0      0    8.6625         0    1             2
159       3    NaN      8      2   69.5500         0    1             2
160       3  44.00      0      1   16.1000         0    1             2
161       2  40.00      0      0   15.7500         1    0             2
162       3  26.00      0      0    7.7750         0    1             2
163       3  17.00      0      0    8.6625         0    1             2
164       3   1.00      4      1   39.6875         0    1             2
165       3   9.00      0      2   20.5250         1    1             2
166       1    NaN      0      1   55.0000         1    0             2
167       3  45.00      1      4   27.9000         0    0             2
168       1    NaN      0      0   25.9250         0    1             2
169       3  28.00      0      0   56.4958         0    1             2
170       1  61.00      0      0   33.5000         0    1             2
171       3   4.00      4      1   29.1250         0    1             1
172       3   1.00      1      1   11.1333         1    0             2
173       3  21.00      0      0    7.9250         0    1             2
174       1  56.00      0      0   30.6958         0    1             0
175       3  18.00      1      1    7.8542         0    1             2
176       3    NaN      3      1   25.4667         0    1             2
177       1  50.00      0      0   28.7125         0    0             0
178       2  30.00      0      0   13.0000         0    1             2
179       3  36.00      0      0    0.0000         0    1             2
180       3    NaN      8      2   69.5500         0    0             2
181       2    NaN      0      0   15.0500         0    1             0
182       3   9.00      4      2   31.3875         0    1             2
183       2   1.00      2      1   39.0000         1    1             2
184       3   4.00      0      2   22.0250         1    0             2
185       1    NaN      0      0   50.0000         0    1             2
186       3    NaN      1      0   15.5000         1    0             1
187       1  45.00      0      0   26.5500         1    1             2
188       3  40.00      1      1   15.5000         0    1             1
189       3  36.00      0      0    7.8958         0    1             2
190       2  32.00      0      0   13.0000         1    0             2
191       2  19.00      0      0   13.0000         0    1             2
192       3  19.00      1      0    7.8542         1    0             2
193       2   3.00      1      1   26.0000         1    1             2
194       1  44.00      0      0   27.7208         1    0             0
195       1  58.00      0      0  146.5208         1    0             0
196       3    NaN      0      0    7.7500         0    1             1
197       3  42.00      0      1    8.4042         0    1             2
198       3    NaN      0      0    7.7500         1    0             1
199       2  24.00      0      0   13.0000         0    0             2
200       3  28.00      0      0    9.5000         0    1             2
201       3    NaN      8      2   69.5500         0    1             2
202       3  34.00      0      0    6.4958         0    1             2
203       3  45.50      0      0    7.2250         0    1             0
204       3  18.00      0      0    8.0500         1    1             2
205       3   2.00      0      1   10.4625         0    0             2
206       3  32.00      1      0   15.8500         0    1             2
207       3  26.00      0      0   18.7875         1    1             0
208       3  16.00      0      0    7.7500         1    0             1
209       1  40.00      0      0   31.0000         1    1             0
210       3  24.00      0      0    7.0500         0    1             2
211       2  35.00      0      0   21.0000         1    0             2
212       3  22.00      0      0    7.2500         0    1             2
213       2  30.00      0      0   13.0000         0    1             2
214       3    NaN      1      0    7.7500         0    1             1
215       1  31.00      1      0  113.2750         1    0             0
216       3  27.00      0      0    7.9250         1    0             2
217       2  42.00      1      0   27.0000         0    1             2
218       1  32.00      0      0   76.2917         1    0             0
219       2  30.00      0      0   10.5000         0    1             2
220       3  16.00      0      0    8.0500         1    1             2
221       2  27.00      0      0   13.0000         0    1             2
222       3  51.00      0      0    8.0500         0    1             2
223       3    NaN      0      0    7.8958         0    1             2
224       1  38.00      1      0   90.0000         1    1             2
225       3  22.00      0      0    9.3500         0    1             2
226       2  19.00      0      0   10.5000         1    1             2
227       3  20.50      0      0    7.2500         0    1             2
228       2  18.00      0      0   13.0000         0    1             2
229       3    NaN      3      1   25.4667         0    0             2
230       1  35.00      1      0   83.4750         1    0             2
231       3  29.00      0      0    7.7750         0    1             2
232       2  59.00      0      0   13.5000         0    1             2
233       3   5.00      4      2   31.3875         1    0             2
234       2  24.00      0      0   10.5000         0    1             2
235       3    NaN      0      0    7.5500         0    0             2
236       2  44.00      1      0   26.0000         0    1             2
237       2   8.00      0      2   26.2500         1    0             2
238       2  19.00      0      0   10.5000         0    1             2
239       2  33.00      0      0   12.2750         0    1             2
240       3    NaN      1      0   14.4542         0    0             0
241       3    NaN      1      0   15.5000         1    0             1
242       2  29.00      0      0   10.5000         0    1             2
243       3  22.00      0      0    7.1250         0    1             2
244       3  30.00      0      0    7.2250         0    1             0
245       1  44.00      2      0   90.0000         0    1             1
246       3  25.00      0      0    7.7750         0    0             2
247       2  24.00      0      2   14.5000         1    0             2
248       1  37.00      1      1   52.5542         1    1             2
249       2  54.00      1      0   26.0000         0    1             2
250       3    NaN      0      0    7.2500         0    1             2
251       3  29.00      1      1   10.4625         0    0             2
252       1  62.00      0      0   26.5500         0    1             2
253       3  30.00      1      0   16.1000         0    1             2
254       3  41.00      0      2   20.2125         0    0             2
255       3  29.00      0      2   15.2458         1    0             0
256       1    NaN      0      0   79.2000         1    0             0
257       1  30.00      0      0   86.5000         1    0             2
258       1  35.00      0      0  512.3292         1    0             0
259       2  50.00      0      1   26.0000         1    0             2
260       3    NaN      0      0    7.7500         0    1             1
261       3   3.00      4      2   31.3875         1    1             2
262       1  52.00      1      1   79.6500         0    1             2
263       1  40.00      0      0    0.0000         0    1             2
264       3    NaN      0      0    7.7500         0    0             1
265       2  36.00      0      0   10.5000         0    1             2
266       3  16.00      4      1   39.6875         0    1             2
267       3  25.00      1      0    7.7750         1    1             2
268       1  58.00      0      1  153.4625         1    0             2
269       1  35.00      0      0  135.6333         1    0             2
270       1    NaN      0      0   31.0000         0    1             2
271       3  25.00      0      0    0.0000         1    1             2
272       2  41.00      0      1   19.5000         1    0             2
273       1  37.00      0      1   29.7000         0    1             0
274       3    NaN      0      0    7.7500         1    0             1
275       1  63.00      1      0   77.9583         1    0             2
276       3  45.00      0      0    7.7500         0    0             2

In [55]:
df.dropna(subset=['Embarked'],inplace = True)
df.shape

(889, 12)

In [37]:
for i in features.columns:
    if (features[i].dtype != object):
        print(i,"vs survived", features[i].corr(features['Survived']))

Pclass vs survived -0.3384810359610147
Age vs survived -0.07722109457217764
SibSp vs survived -0.03532249888573558
Parch vs survived 0.08162940708348365
Fare vs survived 0.2573065223849623
Survived vs survived 1.0
Sex vs survived -0.5433513806577551

In [58]:
print_correlation_list(features)

Pclass vs survived -0.3355488593568253
Age vs survived -0.08244586804341388
SibSp vs survived -0.03403999879674903
Parch vs survived 0.08315078366620243
Fare vs survived 0.2552904613046994
Survived vs survived 1.0
Sex vs survived -0.5415849155511689
embark_value vs survived -0.1697176771641297